"use client";

import { useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

let metadata: Metadata = {
  title: "KFU Health",
  description:
    "Generated by create next app, Tailwind CSS, and love of development from David Akins",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let [isLoggedIn, setIsLoggedIn] = useState<boolean>(true);
  let userTheme = useState<string>("Dark");

  return (
    <html lang="en" className={userTheme[0] === "Dark" ? "dark" : undefined}>
      <head>
        <title>{metadata.title as string}</title>
      </head>
      <body
        className={`${inter.className} bg-white text-black dark:bg-black dark:text-white`}
      >
        {isLoggedIn && (
          <div style={{ marginTop: "20px", marginBottom: "88px" }}>
            <Navbar theme={userTheme} />
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
